apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-docker-test
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: main=localhost:32000/python-docker-test:latest
    argocd-image-updater.argoproj.io/main.force-update: "true"
    argocd-image-updater.argoproj.io/main.update-strategy: digest
spec:
  project: default
  source:
    repoURL: https://github.com/stefanolczak/argocd-test
    targetRevision: HEAD
    path: python-docker-test
  destination: 
    server: https://kubernetes.default.svc
    namespace: bit-arbi
