apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-main
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    chart: redis
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 17.7.3
    helm:
      releaseName: redis-main
      parameters:
      - name: architecture
        value: standalone
      - name: auth.enabled
        value: "false"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: bit-arbi