apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-docker-test
  labels:
    app: python-docker-test
spec:
  selector:
    matchLabels:
      app: python-docker-test
  template:
    metadata:
      labels:
        app: python-docker-test
    spec:
      containers:
      - name: python-docker-test
        image: 10.1.254.64:32000/python-docker-test:3
